### ISSUE TITLE
Errors for AOTAutograd 

### ISSUE THREAD

**Issue by Chillee** [pytorch/torchdynamo#519]
Test command: `./benchmarks/torchbench.py -dcuda --accuracy-aot-nop --inductor-settings --float16  --only model`

- [x] https://github.com/pytorch/functorch/issues/586
"tts_angular",
"demucs",
"tacotron2", # also has an issue with normalize_ir()

- [x] https://github.com/pytorch/torchdynamo/issues/80
"hf_BigBird",

- [x] https://github.com/pytorch/pytorch/issues/81529
"speech_transformer",

- [x] https://github.com/pytorch/pytorch/issues/81526
"moco",

- [x] https://github.com/pytorch/torchdynamo/issues/590
"pyhpc_isoneutral_mixing",

**Comment by Chillee** [comment]
hf_Bart fixed by https://github.com/pytorch/pytorch/pull/81024

**Comment by jansel** [comment]
@Chillee here is my list of AOT autograd issues in TorchInductor.  All confirmed still issues as of today.

- https://github.com/pytorch/functorch/issues/586
"tts_angular",
"demucs",
"tacotron2",  # also has an issue with normalize_ir()
- https://github.com/pytorch/torchdynamo/issues/590
"pyhpc_isoneutral_mixing",
- https://github.com/pytorch/torchdynamo/issues/80
"hf_BigBird",
- https://github.com/pytorch/pytorch/issues/81526
"moco",
- https://github.com/pytorch/pytorch/issues/81529
"speech_transformer",

**Comment by ezyang** [comment]
I've confirmed that dlrm training works with https://github.com/pytorch/pytorch/pull/83330/ plus

```
diff --git a/torch/fx/experimental/proxy_tensor.py b/torch/fx/experimental/proxy_tensor.py
index 7f9f1613c9..60a5d29813 100644
--- a/torch/fx/experimental/proxy_tensor.py
+++ b/torch/fx/experimental/proxy_tensor.py
@@ -60,7 +60,8 @@ def track_tensor_tree(inner_res, proxy_res, *, constant, tracer):
     def wrap_with_proxy(e, proxy, constant):
         if isinstance(e, torch.Tensor):
             track_tensor(e, proxy, tracer=tracer, constant=constant)
-            proxy.node.meta['tensor_meta'] = _extract_tensor_metadata(e)
+            if not e.is_sparse:
+                proxy.node.meta['tensor_meta'] = _extract_tensor_metadata(e)
 
     def get_constant(idx):
         if constant is None:
```

**Comment by ezyang** [comment]
Confirmed moco training also works with the PR `./benchmarks/torchbench.py --no-skip --accuracy-aot-nop -n
 1 -k moco --devices cuda --training`

**Comment by ezyang** [comment]
hf_BigBird training still failing with the PR `./benchmarks/torchbench.py --no-skip --accuracy-aot-nop -n
 1 -k hf_BigBird --devices cuda --training`

```
  File "/raid/ezyang/pytorch-scratch2/functorch/functorch/_src/aot_autograd.py", line 790, in forward
    return compiled_f(
  File "/raid/ezyang/pytorch-scratch2/functorch/functorch/_src/aot_autograd.py", line 776, in new_func
    compiled_fn = create_aot_dispatcher_function(
  File "/raid/ezyang/pytorch-scratch2/functorch/functorch/_src/aot_autograd.py", line 355, in create_aot_dispatcher_function
    aot_dispatch_autograd(flat_fn, fake_flat_tensor_args, aot_config)
  File "/raid/ezyang/pytorch-scratch2/functorch/functorch/_src/aot_autograd.py", line 223, in aot_dispatch_autograd
    out = flat_fn(*flat_args)
  File "/raid/ezyang/pytorch-scratch2/functorch/functorch/_src/aot_autograd.py", line 739, in functional_call
    out = Interpreter(mod).run(*args[params_len:], **kwargs)
  File "/raid/ezyang/pytorch-scratch2/torch/fx/interpreter.py", line 129, in run
    self.env[node] = self.run_node(node)
  File "/raid/ezyang/pytorch-scratch2/torch/fx/interpreter.py", line 162, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/raid/ezyang/pytorch-scratch2/torch/fx/interpreter.py", line 256, in call_method
    return getattr(self_obj, target)(*args_tail, **kwargs)
RuntimeError: set_storage_offset is not allowed on a Tensor created from .data or .detach().
If your intent is to change the metadata of a Tensor (such as sizes / strides / storage / storage_offset)
without autograd tracking the change, remove the .data / .detach() call and wrap the change in a `with torch.no_grad():` block.
For example, change:
    x.data.set_(y)
to:
    with torch.no_grad():
        x.set_(y)
```

**Comment by Chillee** [comment]
I can confirm pyhpc_isoneutral_mixing and moco are now working with aotautograd, although both still fail in inductor for other reasons.

**Comment by ezyang** [comment]
I forgot to fix dlrm, the final fix patch is at https://github.com/pytorch/pytorch/pull/83669

**Comment by ezyang** [comment]
bigbird passes with the repro command here, so only speech_transformer is left

**Comment by ezyang** [comment]
speech_transformer passes with the specified config flags, this issue is all done
